#!/bin/bash

getdefaultsinkvol() {
    pamixer --get-volume
}

getmutestat() {
    pamixer --get-mute
}

setdefaulsinkvol() {
    pamixer --set-volume $1
}

MUTE=$(getmutestat)
VOL=$(getdefaultsinkvol)
DIR="$HOME/.config/Scripts/basic/cat"
STEP=5

case "$1" in
-inc)
    if [ "$MUTE" = "true" ]; then
        pamixer --toggle-mute
    fi
    ((NEWVOL = $VOL + $STEP))
    if [ $NEWVOL -lt 100 ]; then
        pamixer --increase $STEP
        if [ $NEWVOL -gt 90 ]; then
            dunstify -a "Volume" \
                "Volume" \
                "Increase \nVolume: " \
                -h int:value:$NEWVOL \
                -i $DIR/audio-volume-overamplified-symbolic.svg \
                -r 100
        elif [ $NEWVOL -gt 70 ]; then
            dunstify -a "Volume" \
                "Volume" \
                "Increase \nVolume: " \
                -h int:value:$NEWVOL \
                -i $DIR/audio-volume-high-symbolic.svg \
                -r 100
        elif [ $NEWVOL -gt 40 ]; then
            dunstify -a "Volume" \
                "Volume" \
                "Increase \nVolume: " \
                -h int:value:$NEWVOL \
                -i $DIR/audio-volume-medium-symbolic.svg \
                -r 100
        else
            dunstify -a "Volume" \
                "Volume" \
                "Increase \nVolume: " \
                -h int:value:$NEWVOL \
                -i $DIR/audio-volume-muted-symbolic.svg \
                -r 100
        fi
    else
        pamixer --set-volume 100
        dunstify -a "Volume" \
            "Volume" \
            "Increase \nVolume: " \
            -h int:value:100 \
            -i $DIR/audio-volume-overamplified-symbolic.svg \
            -r 100
    fi
    ;;
-dec)
    if [ "$MUTE" = "muted" ]; then
        pamixer --toggle-mute
    fi
    ((NEWVOL = $VOL - $STEP))
    if [ $NEWVOL -gt -1 ]; then
        pamixer --decrease $STEP
        if [ $NEWVOL -gt 100 ]; then
            dunstify -a "Volume" \
                "Volume" \
                "Decrease \nVolume: " \
                -h int:value:$NEWVOL \
                -i $DIR/audio-volume-overamplified-symbolic.svg \
                -r 100
        elif [ $NEWVOL -gt 70 ]; then
            dunstify -a "Volume" \
                "Volume" \
                "Decrease \nVolume: " \
                -h int:value:$NEWVOL \
                -i $DIR/audio-volume-high-symbolic.svg \
                -r 100
        elif [ $NEWVOL -gt 40 ]; then
            dunstify -a "Volume" \
                "Volume" \
                "Decrease \nVolume: " \
                -h int:value:$NEWVOL \
                -i $DIR/audio-volume-medium-symbolic.svg \
                -r 100
        else
            dunstify -a "Volume" \
                "Volume" \
                "Decrease \nVolume: " \
                -h int:value:$NEWVOL \
                -i $DIR/audio-volume-muted-symbolic.svg \
                -r 100
        fi
    else
        pamixer --set-volume 0
        dunstify -a "Volume" \
            "Volume" \
            "Decrease \nVolume: " \
            -h int:value:0 \
            -i $DIR/audio-volume-muted-symbolic.svg \
            -r 100
    fi
    ;;
-mute)
    if [ "$MUTE" = "true" ]; then
        pamixer --toggle-mute
        if [ $VOL -gt 100 ]; then
            dunstify -a "Volume" \
                "Volume" \
                "Current \nVolume: " \
                -h int:value:$VOL \
                -i $DIR/audio-volume-overamplified-symbolic.svg \
                -r 100
        elif [ $VOL -gt 70 ]; then
            dunstify -a "Volume" \
                "Volume" \
                "Current \nVolume: " \
                -h int:value:$VOL \
                -i $DIR/audio-volume-high-symbolic.svg \
                -r 100
        elif [ $VOL -gt 40 ]; then
            dunstify -a "Volume" \
                "Volume" \
                "Current \nVolume: " \
                -h int:value:$VOL \
                -i $DIR/audio-volume-medium-symbolic.svg \
                -r 100
        else
            dunstify -a "Volume" \
                "Volume" \
                "Current \nVolume: " \
                -h int:value:$VOL \
                -i $DIR/audio-volume-muted-symbolic.svg \
                -r 100
        fi
    else
        pamixer --toggle-mute 
        dunstify -a "Volume" \
            "Volume" \
            "Mute \nVolume" \
            -r 100 \
            -i $DIR/audio-volume-mute.png
    fi
    ;;
*)
    exit 1
    ;;
esac
