#!/usr/bin/env bash

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
if [  -f "${_path}/src/_dm-helper.sh" ]; then
  # shellcheck disable=SC1090,SC1091
  . "${_path}/src/_dm-helper.sh"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
. "$(get_config)"


main() {
  # As this is loaded from other file it is technically not defined
  # shellcheck disable=SC2154 # Choosing  a search engine by name from array above.
  bookmarks=$(printf '%s\n' "${!bookmarks_list[@]}" | sort | ${DMENU} -i -l 20 -p 'Bookmarks:') "$@" || exit 1

  # Getting the URL of the chosen search.
  url="${bookmarks_list[${bookmarks}]}"

  # shellcheck disable=SC2154
  ${DMBROWSER} "${url}"
}

[ "${BASH_SOURCE[0]}" = "${0}" ] && main "$@"
