# Don't print a new line at the start of the prompt
add_newline = false
command_timeout = 10000

# Replace the "❯" symbol in the prompt
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[](bold green)[](bold yellow)[](bold red)[](bold purple)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

error_symbol = "[](bold green)[](bold yellow)[](bold red)[](bold red)"

vicmd_symbol = "[](bold yellow)[](bold yellow)[](bold yellow)[](bold yellow)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
symbol = "שׂ "
truncation_length = 4
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
format = '([\[$all_status$ahead_behind \]]($style) )'
conflicted = " 🏳"
ahead = " 🏎💨"
behind = " 😰"
diverged = "[ ](red)"
untracked = "[ ﴕ](blue)"
stashed = " 📦"
modified = "[ פֿ](yellow)"
staged = ' [++\($count\)](green)'
renamed = "[ ](white)"
deleted = "[ ](white)"

[hostname]
ssh_only = false
format =  "on [Arch](bold red) "
trim_at = ".companyname.com"
disabled = true

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed green"

[time]
disabled = true
format = '🕙[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "white bold"
style_root = "black bold"
format = "[samuel]($style) "
disabled = false
show_always = true

[directory]
home_symbol = " "
read_only = "  "
style = "bold blue"
truncation_length = 2
truncation_symbol = "./"
format = "at [$path]($style)[$read_only]($read_only_style) "

[cmd_duration]
disabled = true

[python]
symbol = "🐍 "
format = 'via [${symbol}]($style)'

